### ISSUE TITLE
sddm intermittently does not respond to carriage return on login or lock screen

### ISSUE THREAD

**Issue by PartialVolume** [sddm/sddm#1215]
sddm intermittently does not respond to carriage return on login or lock screen. Carriage return works correctly in all other programs.

I've tried switching themes from kde-sweet back to breeze but that doesn't have any effect.

**System Info:**
KDE Neon 5.17.4
KDE Frameworks Version: 5.64.0
QT Version: 5.13.2
Kernel Version:4.15.0-72-generic
OS Type: 64-bit

**Comment by PartialVolume** [comment]
**Further info:**
It happened after a recent (04/Dec/2019) update that included `kde-config-sddm:amd64 (4:5.17.3-0xneon+18.04+bionic+build41` and `sddm-theme-breeze:amd64 (4:5.17.3-0xneon+18.04+bionic+build52`

**Comment by PartialVolume** [comment]
Also to note. As long as I don't click in the password field and type the password followed by a return it works correctly and responds to the carriage return. However if I click in the password field and then type return it, it fails to respond to the return. So what I was initially seeing as intermittent behavior may have been because sometimes I click in the password field before typing the password and sometimes I don't.

**Comment by ilogs-sepa** [comment]
I am experiencing the same problem.
The keyboard is working and I can type the password but pressing Enter does nothing so I have to commit the password by using the mouse.

**Comment by rbnmndz** [comment]
I noticed several days ago the same problem: the enter key is not working in the sddm-greeter login, although it is working the enter from the numeric keypad. 
I've changed the keyboard to check if it is related to hardware, but no, the problem remains. Nevertheless, the enter key is working normally after login, for example in terminals.
I've checked the keycodes:
keycode 36 (keysym 0xff0d, Return) for normal enter and keycode 104 (keysym 0xff8d, KP_Enter)
for numeric keypad return

$ dpkg -l sddm
ii sddm                              0.17.0-2+18.04+bionic amd64 
but I've just now checked it hasn't been upgraded for at least November December

Instead I've found the package kde-config-sddm has been updated on Dec 3rd
dpkg-l_191203.gz:ii  kde-config-sddm                               4:5.17.3-0xneon+18.04+bionic+build41            amd64        KCM module for SDDM
dpkg-l_191205.gz:ii  kde-config-sddm                               4:5.17.4-0xneon+18.04+bionic+build42
 
$ more /etc/os-release 
NAME="KDE neon"
VERSION="5.17"
ID=neon
ID_LIKE="ubuntu debian"
PRETTY_NAME="KDE neon User Edition 5.17"
VARIANT="User Edition"
VERSION_ID="18.04"

**Comment by franciscot** [comment]
I have the same problem. Sound like this bug closed: https://github.com/sddm/sddm/issues/1107
But in my case the theme is the official from plasma. There are not more ssdm themes installed.

**Comment by PartialVolume** [comment]
One year on from #1107 and I'm seeing this issue on the latest KDE Neon. Due to the nature of this bug and whether you experience it depends on your 'technique' in entering your password.

So assuming your screen has auto locked/blanked and you want to wake up the screen and log in you can do this in three subtly different ways. One of those three ways will show this bug the other two ways won't show the bug.

The three techniques for logging in.

You move the mouse, the login screen appears, you position the mouse cursor in the password box and click left. You type the password and hit return..... Then nothing happens. This technique shows the bug.

You move the mouse, the login screen appears, you DO NOT click in the password box but instead immediately start typing the password and hit return. You're now logged in! This method does not show the bug.

You move the mouse, the login screen appears, you either click left in the password box OR NOT, it doesn't matter which, you enter your password and DO NOT hit return. You click left on the login button. Your're now logged in! This technique does not show the bug.

So I would be interested in anybody that does not have this problem, to try using precisely the steps described in technique 1 above and let's us know whether you can reproduce this bug.

**Comment by gxmobile** [comment]
This issue is very easy to replicate without needing to use the mouse at all as described in the steps above.

To reproduce: at any login screen (either on first login or any time the screen locks) just type in your password **incorrectly**, then press enter. You will get a message that logging in/unlocking failed. Now enter your password again **correctly** and press enter. Nothing happens.

In fact it doesn't matter in the last step if you type the right password or not. Pressing the enter key makes no difference either way. Clicking the "login" button (the arrow to the right of the password field) with the mouse works as expected, however.

This issue has now been duplicated on multiple separate machines (at least two desktop s and three laptops) all running the latest stable version of KDE Neon. This issue did not exist on any of them prior to an update at the beginning of December.

I'd also like to add that this is a significant accessibility issue since users who are not proficient at typing are used to being able to retype their password when they make a mistake, and from my observation will assume that their computer is broken / has crashed when it stops responding on the second enter-press.

For these reasons, I hope a fix for this can be pushed out soon to downstream distros.

**Comment by insanitywholesale** [comment]
I'd like to add that I've been having this issue as well and after a bit of troubleshooting, it's evident that only the enter key that sends the Return keycode doesn't work while the keypad's return key which sends KP_Enter works fine. This is reproducible across at least 2 different installations of KDE Neon and 2 different computers. I hope the information helps in some way

**Comment by iBurley** [comment]
> it's evident that only the enter key that sends the Return keycode doesn't work while the keypad's return key which sends KP_Enter works fine.

Can confirm. When I get the issue I can still get through using the enter key by the numpad. Good catch.

**Comment by rbnmndz** [comment]
It seems it has been solved.
sddm 0.18.1-0+18.04+bionic+build16  @  http://archive.neon.kde.org/user

Operating System: KDE neon 5.18
KDE Plasma Version: 5.18.1
KDE Frameworks Version: 5.67.0
Qt Version: 5.14.1

**Comment by Pointedstick** [comment]
Yup, this was https://bugs.kde.org/show_bug.cgi?id=415130.

**Comment by razorree** [comment]
so it looks like 2y later bugs still exists?  just installed KDE (kde-full on ubuntu 20.10), SDDM as login manager
and after reboot i can enter my password, but it looks like ENTER is not accepted?  (nothing happens)
i can login to system from TTY. but not thru SDDM
(i had to switch to GDM3 to use my system)

KDE Plasna 5.19.5
KDE Frameworks 5.74.0
QT 5.14.2
Kernel 5.8.0-44-generic
qtvirtualkeyboard-plugin/groovy,now 5.14.2+dfsg-2 amd64 [installed,automatic]

**Comment by PartialVolume** [comment]
> so it looks like 2y later bugs still exists? just installed KDE (kde-full on ubuntu 20.10), SDDM as login manager
> and after reboot i can enter my password, but it looks like ENTER is not accepted? (nothing happens)
> i can login to system from TTY. but not thru SDDM

It was definitely fixed in KDE 5.18, which I'm still running, maybe the fix in qtvirtualkeyboard, mentioned above  somehow was not applied to later versions?

**Comment by razorree** [comment]
KDE Plasna 5.19.5
KDE Frameworks 5.74.0
QT 5.14.2
Kernel 5.8.0-44-generic
qtvirtualkeyboard-plugin/groovy,now 5.14.2+dfsg-2 amd64 [installed,automatic]

**Comment by ArthurAttout** [comment]
Encountered this bug today after upgrading my system 
QT 5.15.2
KDE Frameworks 5.78.0
kf5-config 1.0

**Comment by xxidbr9** [comment]
after a couple year i use kde, now im facing the same problem, there is no button for confirm password, and seem my return key doesn’t response anything

**Comment by 103sbavert** [comment]
In 2022, this issue is back

**Comment by PartialVolume** [comment]
I can confirm it's back too. I've found that as long as you **don't** position the cursor in the password and click left then return works. i.e. 100% reproducible if you logout and then as soon as the login screen appears just type the password and hit return. Now logout again, as soon as login screen appears, click left in the password field, type the password and hit return ... nothing happens, unable to login unless you left click on the return icon.

Operating System: KDE neon 5.25
KDE Plasma Version: 5.25.5
KDE Frameworks Version: 5.98.0
Qt Version: 5.15.6
Kernel Version: 5.15.0-48-generic (64-bit)
Graphics Platform: X11
Processors: 20 × 12th Gen Intel® Core™ i7-12700H
Memory: 15.3 GiB of RAM
Graphics Processor: Mesa Intel® Graphics
Manufacturer: Novatech
Product Name: NP5x_NP6x_NP7xPNP
System Version: Not Applicable

**Comment by nekromoff** [comment]
Same problem here, Enter does not work, mouse click must be used to login.
Using real, not virtual keyboard.

Operating System: KDE neon 5.26
KDE Plasma Version: 5.26.0
KDE Frameworks Version: 5.98.0
Qt Version: 5.15.6
Kernel Version: 5.15.0-50-generic (64-bit)
Graphics Platform: X11

**Comment by bach001** [comment]
Same problem here. It's clear that Manjaro didn't apply the patch.

**Comment by vic-torr** [comment]
Same problem here, with Manjaro

**Comment by Chemchu** [comment]
Happening to me aswell. Using NixOs. Any news?
