### ISSUE TITLE
NumLock=on in /etc/sddm.conf doesn't work.

### ISSUE THREAD

**Issue by PavelDobCZ23** [sddm/sddm#1830]
I have set up my `/etc/sddm.conf` file expecting to use it to enable NumLock on the login screen by default. I set up the configuration like so:
```
[General]
InputMethod=
Numlock=on
```
and yet, NumLock is still turned off when I get to the login screen after boot.
My basic system info:
```
OS: Fedora Linux 39 (KDE Plasma) x86_64
Kernel: 6.5.11-300.fc39.x86_64 
DE: Plasma 5.27.9 
```
sddm version from dnf list command: `sddm.x86_64  0.20.0-4.fc39  @anaconda`

**Comment by kuunha** [comment]
Same on Tumbleweed
I've fixed by following this: https://github.com/sddm/sddm/issues/1717#issuecomment-1799140279

Create the file **/var/lib/sddm/.config/kcminputrc** with the content:
```
[Keyboard]
NumLock=0
```

Seems like If SDDM is set up to use Wayland with KWin, NumLock is controlled by this file.
Should be fixed when [this](https://invent.kde.org/plasma/sddm-kcm/-/merge_requests/61) gets shipped.

**Comment by REALERvolker1** [comment]
This does not work under other Wayland backends. It does not solve the problem in SDDM itself.

**Comment by Micovec** [comment]
Experiencing the same thing on Hyprland. I believe it's because it hasn't been implemented yet: [waylandkeyboardbackend.cpp](https://github.com/sddm/sddm/blob/b002d02bbe9281b8362fa549991b7581b7758668/src/greeter/waylandkeyboardbackend.cpp#L93-L115)

I'm not expert on Wayland but wouldn't the implementation be very similar to xcb? XKB can be used on Wayland aswell, right? Or am I spitting garbage.

**Comment by japm48** [comment]
This issue in the Ubuntu tracker has some interesting details and workarounds:
https://bugs.launchpad.net/ubuntu/+source/sddm/+bug/2018203
Hopefully it will help the devs pinpoint the root cause of this and produce a fix.

**Comment by byteit101** [comment]
I have hit this too. I have found the following interesting behaviors:

- Pressing Numlock once turns off numlock
- Pressing Numlock twice allows numeric digits to be entered
- Changing VTs resets the numlock status back to startup. IE. pressing numlock twice, then ctrl-alt-f1 ctrl-alt-f7 and numbers don't work again

**Comment by Everest10** [comment]
Same issue here ...

Operating System: Fedora Linux 40
KDE Plasma Version: 6.0.3
KDE Frameworks Version: 6.0.0
Qt Version: 6.6.2
Kernel Version: 6.8.2_tkg_pds (64-bit)
Graphics Platform: Wayland

❯ rpm -qa | grep sddm
sddm-0.21.0-4.fc40.x86_64
kde-settings-sddm-40.0-1.fc40.noarch
sddm-wayland-plasma-6.0.3-1.fc39.noarch
sddm-breeze-6.0.3-1.fc39.noarch
sddm-kcm-6.0.3-1.fc39.x86_64

**Comment by Ruslan-Riazantsev** [comment]
Should it be fixed by now? I have the latest stable Arch and SDDM, but changing /etc/sddm.conf achieves nothing.

**Comment by bromedia** [comment]
I found a fix. Create `/etc/sddm.conf.d/numlock.conf` and add:

```
Numlock=on
```

The reason it is broken, is because the default setting in `/usr/lib/sddm/sddm.conf.d/default.conf` is `Numlock=none`, and the `src/greeter/GreeterApp.cpp` file doesn't have a case for `Numlock=none`.

**Comment by Vogtinator** [comment]
> I found a fix. Create `/etc/sddm.conf.d/numlock.conf` and add:
> 
> ```
> Numlock=on
> ```
> 
> The reason it is broken, is because the default setting in `/usr/lib/sddm/sddm.conf.d/default.conf` is `Numlock=none`, and the `src/greeter/GreeterApp.cpp` file doesn't have a case for `Numlock=none`.

`Numlock=none` means to not touch the numlock state at all. If `Numlock=on` works for you, there is no bug.

**Comment by bromedia** [comment]
> > I found a fix. Create `/etc/sddm.conf.d/numlock.conf` and add:
> > ```
> > Numlock=on
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The reason it is broken, is because the default setting in `/usr/lib/sddm/sddm.conf.d/default.conf` is `Numlock=none`, and the `src/greeter/GreeterApp.cpp` file doesn't have a case for `Numlock=none`.
> 
> `Numlock=none` means to not touch the numlock state at all. If `Numlock=on` works for you, there is no bug.

If that were the case, it'd be fine. But the fact that num lock is actively disabled when the system is restarted, regardless of the state it was in before, means that there must be some sort of bug. Combined with the fact that there are a number of users experiencing the same issue, I'd call that a bug.

It used to be a simple case of setting num lock to "on" in your keyboard settings, and it would do what it's expected to do whenever you restart. It doesn't do that anymore, are we meant to see that as an improvement?

**Comment by byteit101** [comment]
> I found a fix. Create `/etc/sddm.conf.d/numlock.conf` and add:
> 
> ```
> Numlock=on
> ```
> 
> The reason it is broken, is because the default setting in `/usr/lib/sddm/sddm.conf.d/default.conf` is `Numlock=none`, and the `src/greeter/GreeterApp.cpp` file doesn't have a case for `Numlock=none`.

From prior experiments I have this already set, and it doesn't fix it for me

**Comment by Vogtinator** [comment]
> If that were the case, it'd be fine. But the fact that num lock is actively disabled when the system is restarted, regardless of the state it was in before, means that there must be some sort of bug. Combined with the fact that there are a number of users experiencing the same issue, I'd call that a bug.

It's not this bug though. If `Numlock=none` doesn't work, you can open a new report. It's very likely not SDDM's fault but some other component which overrides the numlock state. If you use the wayland greeter, it's simply not implemented.

**Comment by schoenid** [comment]
I had the same problem under Ubuntu Studio 22.04 ... until I found it in my System settings dialog: Hardware -> Input devices -> Keyboard -> Hardware Tab: Numeric block on Plasma-Start: On.
(translated from german ...)
![image](https://github.com/sddm/sddm/assets/15383666/b102b8fc-4b7b-49c7-bb63-c2eac572a283)

Now Numlock is always enabled on start. :)
btw: I've got no idea, where this setting will be stored ... does anyone know it?

```
Operating System: Ubuntu Studio 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 6.5.0-26-lowlatency (64-bit)
Graphics Platform: X11
Processors: 16 × 13th Gen Intel® Core™ i7-13700K
Memory: 62.5 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3060/PCIe/SSE2
```

**Comment by eduarddejong** [comment]
It's all even weirder...

In Arch Linux and I have an early boot numlock hook installed ([https://aur.archlinux.org/packages/mkinitcpio-numlock](url)), which results in numlock being enabled for TTYs, except for the TTY where SDDM runs.

I haven't changed any setting for numlock in SDDM yet though.
And in `/usr/lib/sddm/sddm.conf.d/default.conf` I see this:
```
# Initial NumLock state. Can be on, off or none.
# If property is set to none, numlock won't be changed
# NOTE: Currently ignored if autologin is enabled.
Numlock=none
```
It's neither enabled or disabled by default here. So SDDM shouldn't the touch numlock functionality at all if I didn't tell it to do so.

The strangest thing is this however:
Somehow SDDM _does_ enable the LED light for numlock, but not the numlock function itself. Instead it actively disables it.
So I still have to press it. If I do that one time, numlock will actually be enabled, while the LED stays on.
If I press again, it turns both the LED and the numlock key function of off normally, after which I can turn those on normally as well.

If I logout from KDE back to SDDM, the same problem returns, just like after system startup.

@schoenid Enabling the KDE Plasma setting for numlock is fine regardless, but it is not a real solution if you want to have numlock enabled _before_ login.

**Comment by Dods** [comment]
@eduarddejong Can confirm, on Debian 12, KDE, when set to Numlock=On, the LED gets lit but the actual numbers on number pad do not work. Pressing the NumLock button on keyboard then activates the numberpad, the LED stays on.
Setting the numlock state on KDE settings as well affects only the LED, not the actual numlock key function.
EDIT: Numlock does get enables/disabled with that setting but after login. Before login, only the LED changes.

**Comment by sharjeelmazhar** [comment]
> I found a fix. Create `/etc/sddm.conf.d/numlock.conf` and add:
> 
> ```
> Numlock=on
> ```
> 
> The reason it is broken, is because the default setting in `/usr/lib/sddm/sddm.conf.d/default.conf` is `Numlock=none`, and the `src/greeter/GreeterApp.cpp` file doesn't have a case for `Numlock=none`. 

This works for me, I'm using hyprland-git and hyprdots config from GitHub.

**Comment by JLuszawski** [comment]
> I found a fix. Create `/etc/sddm.conf.d/numlock.conf` and add:
> 
> ```
> Numlock=on
> ```

It works for me, too, and I have a hint for anyone experiencing strange behavior: if you leave any old config file in this directory, like backup file created by editors, e.g.  'default.conf~'  - it is also considered by sddm, and  the result can be hard to predict, as one will mask another.
BTW: Should not only '.conf' files be considered?

sddm version:  0.20.0-2ubuntu4.2 amd64

**Comment by YuvrajTalukdar** [comment]
> > I found a fix. Create `/etc/sddm.conf.d/numlock.conf` and add:
> > ```
> > Numlock=on
> > ```
> 
> It works for me, too, and I have a hint for anyone experiencing strange behavior: if you leave any old config file in this directory, like backup file created by editors, e.g. 'default.conf~' - it is also considered by sddm, and the result can be hard to predict, as one will mask another. BTW: Should not only '.conf' files be considered?
> 
> sddm version: 0.20.0-2ubuntu4.2 amd64

not working for me

> I found a fix. Create `/etc/sddm.conf.d/numlock.conf` and add:
> 
> ```
> Numlock=on
> ```
> 
> The reason it is broken, is because the default setting in `/usr/lib/sddm/sddm.conf.d/default.conf` is `Numlock=none`, and the `src/greeter/GreeterApp.cpp` file doesn't have a case for `Numlock=none`.

Not working for me at least. I tried changing none to on , still not working. Tried creating /etc/sddm.conf.d/numlock.conf and added Numlock=on, again not working.
sddm version is 0.21.0-4 running under wayland.
Enabled wayland for sddm using the following settings under - /etc/sddm.conf.d/10-wayland.conf
[General]
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell

[Wayland]
CompositorCommand=kwin_wayland --drm --no-lockscreen --no-global-shortcuts --locale1

**Comment by cxbignekoc** [comment]
Got the same issue, 
- another Keyboard or add 
- numlock.conf with numlock=on - does't work for me.
- i also tried numlock=on in the kde-setting.conf

```
MX Linux-23.6 -Debian 12.1-KDE-X11-Nvidia-RTX-4070.
KDEPlasma-5.27
kernel:6.14.2-1-liquorix-amd64 (64-bit)
```

My Practice is hitting two times the num-key to activate the numpad on the login screen.

![Image](https://github.com/user-attachments/assets/dbc56f2e-0393-42bc-b90c-830d1aa5435f)

**Comment by Sturdy7435** [comment]
I'm on arch + hyprland, SDDM uses the weston compositor and i'm noticing the issue with yet another quirk:
while the led on my external keyboard shows numlock is on, I still need to toggle it for numbers to work, but the led on my laptop's keyboard always shows the correct numlock status.
Changing options in weston.ini or sddm.conf, as others have noted, has no effect on the behaviour.

**Comment by stoneynutcase** [comment]
lol, whatever I try, this is not working (CachyOS, sddm, KDE Plasma + X11), the only thing that seems to work is the KDE setting.

**Comment by baboo35** [comment]
> the only thing that seems to work is the KDE setting.

For me it works too, when I've pressed "Apply settings from Plasma" in KDE settings => SDDM settings window.

**Comment by stevensko** [comment]
> > the only thing that seems to work is the KDE setting.
> 
> For me it works too, when I've pressed "Apply settings from Plasma" in KDE settings => SDDM settings window.

I didn't understand what you meant until I read someone else explain the same thing differently on reddit:

"In System Settings, go to 'Keyboard', change 'NumLock on startup' option to 'Turn on'. Next in System Settings, go to 'Login screen (SDDM)' under 'Colors & Themes' and click on 'Apply Plasma Settings...' at the top right corner and confirm apply."

**Comment by Discostu36** [comment]
For me, the problem has disappeared since upgrading to MX Linux KDE 25. Adding Numlock=on to sddm.conf now works.

Didn't work in:
- Kernel: 6.13.7-1-liquorix-amd64
- MX-23.5_KDE_x64
- base: Debian GNU/Linux 12 (bookworm)
- KDE Plasma v: 5.27.5

Works in:
- Kernel: 6.12.48+deb13-amd64
- MX-25_KDE_x64
- base: Debian GNU/Linux 13 (trixie)
- KDE Plasma v: 6.3.6

@cxbignekoc How about you?
